api_version: generators.giantswarm.io/v1
app_catalog: control-plane-catalog
app_destination_namespace: monitoring
app_name: prometheus-operator-crd
app_version: 2.0.1
kind: Konfigure
metadata:
  annotations:
    config.kubernetes.io/function: |-
      exec:
        path: /plugins/konfigure
  name: prometheus-operator-crd
name: prometheus-operator-crd
